// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeobfuscateOotbSettings() {
  return window['go']['main']['App']['DeobfuscateOotbSettings']();
}

export function DeobfuscateZdpModes() {
  return window['go']['main']['App']['DeobfuscateZdpModes']();
}

export function DisableAntiTampering() {
  return window['go']['main']['App']['DisableAntiTampering']();
}

export function EnableAntiTampering() {
  return window['go']['main']['App']['EnableAntiTampering']();
}

export function GetAntiTamperingStatus() {
  return window['go']['main']['App']['GetAntiTamperingStatus']();
}

export function GetDetailsHttpCmd() {
  return window['go']['main']['App']['GetDetailsHttpCmd']();
}

export function GetDetailsHttpsCmd() {
  return window['go']['main']['App']['GetDetailsHttpsCmd']();
}

export function IsZdpServiceRunning() {
  return window['go']['main']['App']['IsZdpServiceRunning']();
}
