// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeobfuscateOotbSettings():Promise<string>;

export function DeobfuscateZdpModes():Promise<string>;

export function DisableAntiTampering():Promise<void>;

export function EnableAntiTampering():Promise<void>;

export function GetAntiTamperingStatus():Promise<string>;

export function GetDetailsHttpCmd():Promise<string>;

export function GetDetailsHttpsCmd():Promise<string>;

export function IsZdpServiceRunning():Promise<boolean>;
