// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearZdpLogs():Promise<string>;

export function DeobfuscateOotbSettings():Promise<string>;

export function DeobfuscateZdpModes():Promise<string>;

export function DisableAntiTampering():Promise<void>;

export function EnableAntiTampering():Promise<void>;

export function GetAllVersions():Promise<main.AllVersions>;

export function GetAntiTamperingStatus():Promise<string>;

export function GetCurrentLogLevel():Promise<string>;

export function GetDlpSdkVersion():Promise<string>;

export function GetSaveMessagesLocallyStatus():Promise<boolean>;

export function GetVersion():Promise<string>;

export function IsOotbSettingsObfuscated():Promise<boolean>;

export function IsZdpModesObfuscated():Promise<boolean>;

export function IsZdpServiceRunning():Promise<string>;

export function ReadFileContent(arg1:string):Promise<string>;

export function RegisterDev04(arg1:boolean):Promise<string>;

export function RestartZdpService():Promise<void>;

export function SelectFile():Promise<string>;

export function SetLogLevel(arg1:string):Promise<void>;

export function SetSaveMessagesLocally(arg1:boolean):Promise<string>;

export function StandaloneClassifier(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<main.ClassifierOutput>;

export function StartZdpService():Promise<void>;

export function StopZdpService():Promise<void>;
